### ISSUE TITLE
[ERROR] App - 404 GET /lib/jquery/jquery.min.js

### ISSUE THREAD

**Issue by Kamik** [Infactum/faxserver#2]
при заходе на страницу получаю в логе
[ERROR] App - 404 GET /lib/jquery/jquery.min.js
как лечиться?

**Comment by Infactum** [comment]
Видимо jquery был ошибочно не включен в зависимости.
Можно скачать с офф сайта и положить в каталог public. Только надо аккуратно с выбором версии быть. Писалось все очень давно и я не уверен, что без доработки напильником проект запустится. Все-таки 5 лет для сферы node.js это целая вечность.
